name: AutoBlacklistBan
version: '1.0.0'
main: com.mcblacklist.autoBlacklistBan.AutoBlacklistBan
api-version: '1.21'
commands:
    blacklistnotify:
        description: Main command for AutoBlacklistBan plugin
        usage: /blacklistnotify <remove|grant> <player>
    exemptblacklist:
        description: Exempt a player from being blacklisted
        usage: /exemptblacklist <add|remove> <player>
